name: pullpreview

on:
  push:
    branches:
      - dev
  pull_request:
    types: [labeled, unlabeled, synchronize, closed, reopened]

jobs:
  deploy:
    if: ( github.event_name == 'push' || github.event.label.name == 'pullpreview' || contains(github.event.pull_request.labels.*.name, 'pullpreview') )
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v2
    - uses: pullpreview/action@v4
      with:
        admins: crohr,HDinger,machisuji,oliverguenther,ulferts,wielinde
        always_on: dev
        compose_files: docker-compose.yml,docker-compose.pullpreview.yml
        instance_type: small_2_0
      env:
        AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
        AWS_REGION: eu-central-1
